package class8.ExceptionInSelenium;

public class ExceptionDemo {

	public static void main(String[] args) {

		int [] num = new int[2];
		
		num[0]=10;
		num[1]=20;
		num[2]=30;
		
		System.out.println(num[2]);
		System.out.println("Program end");
	}
}
